server:
  port: 8002
spring:
  application:
    name: link-data
  cloud:
    nacos:
      discovery:
        server-addr: 212.129.255.88:8848
        username: nacos
        password: nacos
  datasource:
    driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
    url: jdbc:clickhouse://212.129.255.88:8123/default

  redis:
    client-type: jedis
    host: 212.129.255.88
    password: pl1008666.
    port: 6379
    jedis:
      pool:
        # 连接池的最大连接数(使用负值表示没有限制)
        max-active: 100
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池中的最小空闲连接
        min-idle: 100
        # 连接池最大阻塞等待时间 (使用复制表示没有限制)
        max-wait: 60000

# 配置mybatis-plus打印sql
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root: info
