server:
  port: 8003
spring:
  application:
    name: link-link
  cloud:
    nacos:
      discovery:
        server-addr: 212.129.255.88:8848
        username: nacos
        password: nacos
  redis:
    client-type: jedis
    host: 212.129.255.88
    password: pl1008666.
    port: 6379
    jedis:
      pool:
        # 连接池的最大连接数(使用负值表示没有限制)
        max-active: 100
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池中的最小空闲连接
        min-idle: 100
        # 连接池最大阻塞等待时间 (使用复制表示没有限制)
        max-wait: 60000

  shardingsphere:
    props:
      # 打印执行的数据库以及语句
      sql:
        show: true
    datasource:
      #数据源名称
      names: ds0,ds1,dsa
      # ds0配置
      ds0:
        connectionTimeoutMilliseconds: 30000
        driver-class-name: com.mysql.cj.jdbc.Driver
        idleTimeoutMilliseconds: 60000
        jdbc-url: jdbc:mysql://212.129.255.88:3306/link_0?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        maintenanceIntervalMilliseconds: 30000
        maxLifetimeMilliseconds: 1800000
        maxPoolSize: 50
        minPoolSize: 50
        username: root
        password: pl1008666.
        type: com.zaxxer.hikari.HikariDataSource
      # ds1配置
      ds1:
        connectionTimeoutMilliseconds: 30000
        driver-class-name: com.mysql.cj.jdbc.Driver
        idleTimeoutMilliseconds: 60000
        jdbc-url: jdbc:mysql://212.129.255.88:3306/link_1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        maintenanceIntervalMilliseconds: 30000
        maxLifetimeMilliseconds: 1800000
        maxPoolSize: 50
        minPoolSize: 50
        username: root
        password: pl1008666.
        type: com.zaxxer.hikari.HikariDataSource
      # dsa配置
      dsa:
        connectionTimeoutMilliseconds: 30000
        driver-class-name: com.mysql.cj.jdbc.Driver
        idleTimeoutMilliseconds: 60000
        jdbc-url: jdbc:mysql://212.129.255.88:3306/link_a?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        maintenanceIntervalMilliseconds: 30000
        maxLifetimeMilliseconds: 1800000
        maxPoolSize: 50
        minPoolSize: 50
        username: root
        password: pl1008666.
        type: com.zaxxer.hikari.HikariDataSource

    sharding:
      tables:
        link_group:
          #分库策略
          database-strategy:
            inline:
              sharding-column: account_no
              algorithm-expression: ds$->{account_no % 2}
          #id生成策略
          key-generator:
            column: id
            props:
              worker:
                id: ${workId}
            #id生成策略
            type: SNOWFLAKE
        # 先进行水平分库，然后再进行水平分表
        short_link:
          database-strategy:
            standard:
              sharding-column: code
              precise-algorithm-class-name: com.example.shortlink.link.strategy.CustomDBPreciseShardingAlgorithm
          # 真实库，逻辑表
          actual-data-nodes: ds0.short_link,ds1.short_link,dsa.short_link
          table-strategy:
            standard:
              sharding-column: code
              precise-algorithm-class-name: com.example.shortlink.link.strategy.CustomTablePreciseShardingAlgorithm

          # id生成策略
          key-generator:
            column: id
            type: SNOWFLAKE
            props:
              worker:
                id: ${workId}



