server:
  port: 8005
spring:
  application:
    name: link-shop
  cloud:
    nacos:
      discovery:
        server-addr: 212.129.255.88:8848
        username: nacos
        password: nacos
  # redis连接
  redis:
    client-type: jedis
    host: 212.129.255.88
    password: pl1008666.
    port: 6379
    jedis:
      pool:
        # 连接池的最大连接数(使用负值表示没有限制)
        max-active: 100
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池中的最小空闲连接
        min-idle: 100
        # 连接池最大阻塞等待时间 (使用复制表示没有限制)
        max-wait: 60000
  shardingsphere:
    datasource:
      #数据源名称
      names: ds0
      ds0:
        connectionTimeoutMilliseconds: 30000
        driver-class-name: com.mysql.cj.jdbc.Driver
        idleTimeoutMilliseconds: 60000
        jdbc-url: jdbc:mysql://212.129.255.88:3306/link_shop?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        maintenanceIntervalMilliseconds: 30000
        maxLifetimeMilliseconds: 1800000
        maxPoolSize: 50
        minPoolSize: 50
        username: root
        password: pl1008666.
        type: com.zaxxer.hikari.HikariDataSource
    props:
      # 打印执行的数据库以及语句
      sql:
        show: true
    sharding:
      # 配置默认数据库
      default-data-source-name: ds0
      # 默认id生成策略
      default-key-generator:
        column: id
        type: SNOWFLAKE
        props:
          worker:
            id: ${workId}
      tables:
        product_order:
          actual-data-nodes: ds0.product_order_$->{0..1}
          # 水平分表策略
          table-strategy:
            inline:
              algorithm-expression: product_order_$->{account_no % 2}
              sharding-column: account_no

  # rabbitmq 配置
  rabbitmq:
    host: 212.129.255.88
    port: 5672
    # 需要手工创建虚拟机
    virtual-host: dev
    username: admin
    password: pl1008666.
    # 消息确认方式 manual(手动ack) auto 自动ack 消息消费重试达到指定次数进到异常交换机和异常队列，需要改为自动确认消息
    listener:
      simple:
        acknowledge-mode: auto
        # 开启重试机制
        retry:
          enabled: true
          # 最大重试次数
          max-attempts: 4
          # 重试消息的时间间隔 5秒
          initial-interval: 5000

# 微信支付
pay:
  wechat:
    mch-id: 1558950191
    wx-pay-appid: wx74862e0dfcf69954
    mch-serial-no: 34345964330B66427E0D3D28826C4993C77E631F
    api-v3-key: UDuLFDcmy5Eb6o0nTNZdu6ek4DDh4K8B
    # 自定义
    private-key-path: classpath:/cert/apiclient_key.pem
    success-return-url: https://www.nit.edu.cn
    callback-url: http://cjwjb9.natappfree.cc/api/callback/order/v1/wechat

